### ISSUE TITLE
Compiled for Linux

### ISSUE THREAD

**Issue by ghost** [leodenglovescode/hackgen#1]
Not really an issue but I've compiled this program for Linux, if your interested in adding it to the release page then let me know and I'll send the link. I've tested the features and they seem to work fine.

**Comment by leodenglovescode** [comment]
Oh really? Thanks A lot! I've been working for a day to get the linux version working but it still does not seem to work, your's might be a perfect version! can you please send me the link or file in a zip to this address? leodeng_hack@163.com

**Comment by ghost** [comment]
Here! https://mega.nz/file/7AhWlJgD#ukHgAcZj_-c1dq0s3qn7nkksQerYGCj5jzrOveEF0QY

Compiled on Arch Linux using PyInstaller
Kernel Version: 5.17.9-arch1-1

No modifications to the main python file were made, and I tested the features to make sure they work.
